substitutions:
  _REGION: us-central1
  _SERVICE_ACCOUNT: xrpl-token-sa@${PROJECT_ID}.iam.gserviceaccount.com
  _XRPL_NETWORK: testnet
  _SIGNING_PROVIDER: sm

steps:
  # 1. Deploy bank service
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-bank"
    args:
      - "run"
      - "deploy"
      - "xrpl-bank"
      - "--source=."
      - "--region=${_REGION}"
      - "--service-account=${_SERVICE_ACCOUNT}"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--max-instances=2"
      - "--min-instances=1"
      - "--set-env-vars=SERVICE=bank,NODE_ENV=staging,LOG_LEVEL=info,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},BANK_JWT_SECRET_PATH=projects/${PROJECT_ID}/secrets/bank-jwt-secret/versions/latest"
      - "--startup-probe=httpGet.path=/health,httpGet.port=8080,periodSeconds=10"
      - "--liveness-probe=httpGet.path=/health,httpGet.port=8080,periodSeconds=300"
      - "--ingress=all"
      - "--allow-unauthenticated"

  # 2. Get bank service URL → deploy token service
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-token"
    waitFor: ["deploy-bank"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        BANK_URL=$(gcloud run services describe xrpl-bank \
          --region=${_REGION} --format='value(status.url)')
        gcloud run deploy xrpl-token \
          --source=. \
          --region=${_REGION} \
          --service-account=${_SERVICE_ACCOUNT} \
          --memory=512Mi \
          --cpu=1 \
          --max-instances=2 \
          --min-instances=1 \
          --set-env-vars="\
        SERVICE=token,\
        NODE_ENV=staging,\
        LOG_LEVEL=info,\
        GOOGLE_CLOUD_PROJECT=${PROJECT_ID},\
        XRPL_NETWORK=${_XRPL_NETWORK},\
        SIGNING_PROVIDER=${_SIGNING_PROVIDER},\
        BANK_SERVICE_URL=$$BANK_URL,\
        MNEMONIC_SECRET_PATH=projects/${PROJECT_ID}/secrets/xrpl-mnemonic/versions/latest,\
        BANK_AUTH_TOKEN_SECRET_PATH=projects/${PROJECT_ID}/secrets/bank-auth-token/versions/latest,\
        MFA_TOKEN_SECRET_PATH=projects/${PROJECT_ID}/secrets/mfa-token-secret/versions/latest,\
        JPYN_ISSUER_ADDRESS=$${JPYN_ISSUER_ADDRESS},\
        JPYN_KMS_KEY_PATH=projects/${PROJECT_ID}/secrets/xrpl-issuer-seed/versions/latest,\
        JPYN_SIGNING_PUBLIC_KEY=$${JPYN_SIGNING_PUBLIC_KEY},\
        ISSUER_DOMAIN=$${ISSUER_DOMAIN}" \
          --startup-probe=httpGet.path=/health,httpGet.port=8080,periodSeconds=10 \
          --liveness-probe=httpGet.path=/health,httpGet.port=8080,periodSeconds=300 \
          --ingress=all \
          --allow-unauthenticated

  # 3. Setup Pub/Sub: bank deposit events → token service
  - name: "gcr.io/cloud-builders/gcloud"
    id: "setup-pubsub"
    waitFor: ["deploy-token"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        TOKEN_URL=$(gcloud run services describe xrpl-token \
          --region=${_REGION} --format='value(status.url)')
        gcloud pubsub topics describe bank-deposit-events 2>/dev/null || \
          gcloud pubsub topics create bank-deposit-events
        if gcloud pubsub subscriptions describe bank-deposit-push 2>/dev/null; then
          gcloud pubsub subscriptions update bank-deposit-push \
            --push-endpoint="$$TOKEN_URL/api/v1/pubsub/bank/deposit" \
            --push-auth-service-account=${_SERVICE_ACCOUNT}
        else
          gcloud pubsub subscriptions create bank-deposit-push \
            --topic=bank-deposit-events \
            --push-endpoint="$$TOKEN_URL/api/v1/pubsub/bank/deposit" \
            --push-auth-service-account=${_SERVICE_ACCOUNT} \
            --ack-deadline=60 \
            --min-retry-delay=10s \
            --max-retry-delay=600s
        fi

  # 4. Setup Eventarc: Firestore tokenTransactions → token service
  - name: "gcr.io/cloud-builders/gcloud"
    id: "setup-eventarc"
    waitFor: ["deploy-token"]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if gcloud eventarc triggers describe xrpl-token-deposit \
          --location=${_REGION} 2>/dev/null; then
          gcloud eventarc triggers update xrpl-token-deposit \
            --location=${_REGION} \
            --destination-run-service=xrpl-token \
            --destination-run-region=${_REGION} \
            --destination-run-path=/api/v1/eventarc/xrpl/deposit \
            --service-account=${_SERVICE_ACCOUNT}
        else
          gcloud eventarc triggers create xrpl-token-deposit \
            --location=${_REGION} \
            --destination-run-service=xrpl-token \
            --destination-run-region=${_REGION} \
            --destination-run-path=/api/v1/eventarc/xrpl/deposit \
            --event-filters="type=google.cloud.firestore.document.v1.created" \
            --event-filters="database=(default)" \
            --event-filters-path-pattern="document=tokenTransactions/{txHash}" \
            --event-data-content-type="application/protobuf" \
            --service-account=${_SERVICE_ACCOUNT}
        fi

options:
  logging: CLOUD_LOGGING_ONLY
